config/routes.rb
FourEyes::Engine.routes.draw do
  resources :actions, only: [:index, :show]
end

app/models/four_eyes/action.rb
module FourEyes
  class Action < ActiveRecord::Base
    validates :action_type, :status, presence: true

    belongs_to :maker, polymorphic: true
    belongs_to :checker, polymorphic: true, optional: true
    belongs_to :assignable, polymorphic: true, optional: true
    belongs_to :object_resource, polymorphic: true, optional: true

    has_many :attachments, class_name: "FourEyes::Attachment", foreign_key: "four_eyes_action_id"

    def self.between_times(start_time, end_time)
      Action.where('created_at >= ? AND created_at < ?', start_time, end_time)
    end

    def initiated?
      self.status == 'Initiated'
    end

    def cancelled?
      self.status == 'Cancelled'
    end

    def authorized?
      self.status == 'Authorized'
    end
  end
end

app/models/four_eyes/attachment.rb
module FourEyes
  class Attachment < ActiveRecord::Base
    validates :name, presence: true

    belongs_to :action, class_name: "FourEyes::Action", foreign_key: "four_eyes_action_id"

    has_many_attached :pages
  end
end

app/controllers/four_eyes/actions_controller.rb
module FourEyes
  # This controller provides restful route handling for Actions.
  #
  # == Security:
  # Only GET requests are supported. You should ensure that your application
  # controller enforces its own authentication and authorization, which this
  # controller will inherit.
  #
  # @author Dennis Ondeng
  class ActionsController < ApplicationController
    include FourEyes::Concerns::Controllers::Actions
  end
end

app/controllers/four_eyes/application_controller.rb
module FourEyes
  class ApplicationController < ActionController::Base
  end
end

app/helpers/four_eyes/application_helper.rb
module FourEyes
  module ApplicationHelper
  end
end

app/views/four_eyes/actions/index.html.erb
<div class="four_eyes_container">
  <h1>Actions</h1>

  <table cellspacing="0">
    <thead>
    <tr>
      <th class="nobg">ID</th>
      <th>Date</th>
      <th>Action</th>
      <th>Maker ID</th>
      <th>Object</th>
      <th>Status</th>
      <th>Data</th>
    </tr>
    </thead>
    <tbody>
    <% @actions.each do |action| %>
        <tr class="<%= cycle("even", "odd") -%>">
          <td><%=link_to(action.id, action_path(action)) %></td>
          <td><%= action.created_at %></td>
          <td><%=h action.action_type %></td>
          <td><%=h action.maker_id  %></td>
          <td><%=h action.object_resource_type  %></td>
          <td><%=h action.status  %></td>
          <td><%=h action.data %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/four_eyes/actions/show.html.erb
<div class="four_eyes_container">
  <h1>Action</h1>

  <table>
    <tr>
      <td>ID</td>
      <td><%= @action.id %></td>
    </tr>
    <tr>
      <td>Date</td>
      <td><%= @action.created_at %></td>
    </tr>
    <tr>
      <td>Action</td>
      <td><%= @action.action_type %></td>
    </tr>
    <tr>
    <td>Maker </td>
    <td><%= @action.maker_type %></td>
  </tr>
    <tr>
      <td>Maker ID</td>
      <td><%= @action.maker_id %></td>
    </tr>

    <tr>
      <td>Assignee </td>
      <td><%= @action.assignable_type %></td>
    </tr>
    <tr>
      <td>Assignee ID</td>
      <td><%= @action.assignable_id %></td>
    </tr>

    <tr>
      <td>Checker </td>
      <td><%= @action.checker_type %></td>
    </tr>
    <tr>
      <td>Checker ID</td>
      <td><%= @action.checker_id %></td>
    </tr>
    <tr>
      <td>Object</td>
      <td><%= @action.object_resource_type %></td>
    </tr>
    <tr>
      <td>Object ID</td>
      <td><%= @action.object_resource_id %></td>
    </tr>
    <tr>
      <td>Data</td>
      <td><%= @action.data.to_s %></td>
    </tr>
    <tr>
      <td>Status</td>
      <td><%= @action.status %></td>
    </tr>
  </table>
</div>